app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_change_password:
    resource: '@FOSUserBundle/Resources/config/routing/change_password.xml'

fos_resetting:
    resource: '@FOSUserBundle/Resources/config/routing/resetting.xml'

fos_user_resetting_check_email:
    path: /check-email
    defaults: { _controller: AppBundle:Security:checkEmail }

static_pages:
    resource: 'routing_static_pages.yml'