# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    authentication_handler:
        class:  AppBundle\Security\FOSAuthenticationHandler
        arguments:  ['@router']

    registration_subscriber:
        class: AppBundle\Security\FOSRegistrationSubscriber
        arguments: ['@router', '@session.flash_bag']
        tags:
            - { name: kernel.event_subscriber }

    logout_listener:
        class: AppBundle\Security\LogoutListener
        autowire: ['@router']