# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    insert_lesson_listener:
        class: AppBundle\EventListener\CategoryUpdater
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    authentication_handler:
        class:  AppBundle\Security\FOSAuthenticationHandler
        arguments:  ['@router']

    registration_subscriber:
        class: AppBundle\Security\FOSRegistrationSubscriber
        tags:
            - { name: kernel.event_subscriber }
