# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.security.login_form_authenticator:
        class: AppBundle\Security\LoginFormAuthenticator
        autowire: true

    app.security.logout_handler:
        class: AppBundle\Security\LogoutHandler

    app.fos_user_listener:
        class: AppBundle\FosUser\FosUserListener
        autowire: true
        tags:
            - { name: kernel.event_subscriber }
