app.static.guidance:
    path: /guidance
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/guidance.html.twig

app.static.speaking:
    path: /speaking
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/speaking.html.twig
