AppBundle\Entity\SavedLesson:
    type: entity
    table: saved_lesson
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        point:
            type: smallint
    manyToOne:
        user:
            targetEntity: User
            inversedBy: progress
        lesson:
            targetEntity: Lesson
    oneToMany:
        savedSentences:
            targetEntity: SavedSentence
            mappedBy: savedLesson
