AppBundle\Entity\Sentence:
    type: entity
    repositoryClass: AppBundle\Repository\SentenceRepository
    table: sentence
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        content:
            type: string
        json_content:
            type: json_array
        point:
            type: smallint
            options:
                unsigned: true
                default: 0
        position:
            type: smallint
            options:
                unsigned: true
                default: 0
        audioPath:
            type: string
    manyToOne:
        lesson:
            targetEntity: Lesson
            inversedBy: sentences
            joinColumn: lesson_id
            referencedColumnName: id
