AppBundle\Entity\User:
    type: entity
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        point:
            type: int
            options:
                unsigned: true
                default: 0
        createdAt:
            type: date
        updatedAt:
            type: datetime
    oneToMany:
        savedLessons:
            targetEntity: SavedLesson
            mappedBy: user
        doneLessons:
            targetEntity: DoneLesson
            mappedBy: user
        progress:
            targetEntity: Progress
            mappedBy: user
